name: vecalign
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.7
  - numpy
  - cython
  - pytorch
  - pip:
    - fastBPE
    - Flask
    - Flask-Cors
    - transliterate
    - jieba
    - underthesea
    - hanziconv
    
